### ISSUE TITLE
Fail to create Transcription document

### ISSUE THREAD

**Issue by baardl** [nrkno/transcriber-backend#18]

**Comment by baardl** [comment]
default.updateTranscript is not a function
    at app.post (webpack:///./src/api/authenticatedApi.ts?:228:53)
    at Layer.handle [as handle_request] (/srv/node_modules/express/lib/router/layer.js:95:5)
    at next (/srv/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/srv/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/srv/node_modules/express/lib/router/layer.js:95:5)
    at /srv/node_modules/express/lib/router/index.js:281:22
    at param (/srv/node_modules/express/lib/router/index.js:354:14)
    at param (/srv/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/srv/node_modules/express/lib/router/index.js:410:3)
    at next (/srv/node_modules/express/lib/router/index.js:275:10)
